window.Portfolio = window.Portfolio || {};
window.Portfolio.POST_CONTENT = {
  id: 'oauth-lessons',
  content: `
    <p>The OAuth 2.0 specification is thorough, well-reasoned, and genuinely good engineering. It is also spectacularly unhelpful when you're staring at a four-hundred-and-one at eleven PM trying to figure out why Okta is rejecting a perfectly valid token that worked fine with Google five minutes ago. The spec tells you what the protocol is. It does not tell you what major providers actually do with it.</p>
    <p>After integrating SSO for more than a dozen clients across Google, Okta, and Azure — and spending an embarrassing number of hours debugging issues that weren't in any documentation — here are the five gaps between the RFC and reality that cost me the most time.</p>

    <h2>Token Expiry Is a Suggestion</h2>
    <p>Providers are supposed to honour the <code>expires_in</code> field in the token response. In practice, Okta will sometimes invalidate tokens earlier if the user's session is revoked at the IdP level — for example, if an admin forces a logout or the user's account is suspended between when the token was issued and when it's used. Azure has its own notion of "token lifetime policies" that can be configured by administrators to override what your application expects based on the spec.</p>
    <p>The practical consequence: you must build your token refresh logic to handle a four-hundred-and-one at any time, not just when the token is technically expired according to its <code>expires_in</code> value. Every authenticated API call should be wrapped in middleware that catches four-hundred-and-ones, attempts a silent refresh, and retries exactly once. If the refresh fails, redirect to login. This pattern handles almost every real-world token failure gracefully.</p>

    <h2>The Redirect URI Must Be Exact</h2>
    <p>Not "basically the same." Not "the same path with a different query string." Not "the same domain with a different port." Character for character, including trailing slashes, including protocol case, including whether www is present. The OAuth spec requires this for security reasons — it prevents authorization code interception via open redirectors — but the error messages you get when it fails are almost completely uninformative. "Redirect URI mismatch" tells you something is wrong. It does not tell you that the trailing slash you added to your development environment config three weeks ago is now breaking production.</p>
    <p>Maintain a registry of all your redirect URIs in a configuration file that's checked into version control. Every environment — development, staging, production — should have its URIs explicitly listed and reviewed. When you add a new one, add it to the provider's allowed list first, before deploying the code that uses it. The five minutes of discipline prevents an hour of debugging.</p>

    <h2>PKCE Is Not Optional Anymore</h2>
    <p>PKCE — Proof Key for Code Exchange — was originally designed for mobile apps that couldn't securely store a client secret. The threat model: an attacker intercepts the authorization code before it can be exchanged for a token. PKCE prevents this by requiring the client to prove it's the same client that initiated the flow, using a one-time verifier that never leaves the client.</p>
    <p>Modern security guidance treats PKCE as mandatory for all public clients, including browser-based applications. If your OAuth flow doesn't use PKCE, you're vulnerable to authorization code interception attacks in any environment where the redirect can be observed. Most providers still accept flows without it for backwards compatibility. They shouldn't, and neither should you. The implementation overhead is minimal — generate a random code verifier, hash it to create the code challenge, include both in the appropriate places — and the security improvement is meaningful.</p>

    <h2>Scopes Are Provider-Specific</h2>
    <p>The OAuth spec defines a framework for scopes. It does not define what the scopes mean. The <code>email</code> scope returns different fields from Google, Microsoft, and Okta. <code>profile</code> might include a phone number on one provider and not on another. <code>openid</code> is standardised by OIDC, but the claims included in the ID token vary. Some providers require an additional scope to get the user's name. Some include it in <code>profile</code>. Some return it only if you also request <code>email</code>.</p>
    <p>The only reliable approach is to test your user info endpoint response against every provider you support and map the fields explicitly. Never assume that a field present in the Google response will be present in the Okta response for the same set of scopes. Build your user profile normalization layer before you need it — retrofitting it after you've already shipped support for three providers is significantly more painful.</p>

    <h2>Logout Is Genuinely Hard</h2>
    <p>Logging out of your application does not log the user out of the identity provider. This surprises more developers than it should. The user can close your app, reopen it, and get a new token immediately without re-authenticating — because their IdP session is still active. Clearing your application's cookies and token storage is a local operation. The session at the identity provider is a separate, independent state that you don't own.</p>
    <p>For most consumer applications, this is acceptable or even desirable — users expect a "sign in with Google" to feel seamless. For enterprise applications with security requirements around session termination, it's a genuine gap. The OpenID Connect Front-Channel Logout and Back-Channel Logout specifications address this, and they're supported by all major enterprise identity providers. They're also vastly underused, mostly because they're slightly more complex to implement and the gap is invisible until someone's security audit surfaces it.</p>
    <p>The practical advice: decide early whether your security requirements need real session termination, document that decision, and implement accordingly. Retrofitting logout behaviour into an application that assumed it didn't matter is a non-trivial exercise.</p>
  `
};
